name: Create Azure Resources
on: 
  push:
    branches:
      - main  # or specify the branch you want to trigger on
    paths: 
      - 'ARM/**'
      - '.github/workflows/infraworkflow.yml'

env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    AZURE_RESOURCEGROUP_NAME: myResourceGroup                      # Your resource group name
    AZURE_WEBAPP_NAME: demo-webappsql-gh-actions-unique          # Your web app name
    ASP_NAME: demo-webappsql-gh-actions
    SQLSERVER_NAME: demo-webappsql-gh-actions-srv                # Your SQL server name
    DATABASE_NAME: demo-webappsql-gh-actions-db                  # Your database name
    SQLADMIN_LOGIN: ${{ secrets.SQLADMIN_LOGIN }}                # SQL Admin login secret
    SQLADMIN_PASS: ${{ secrets.SQLADMIN_PASS }}                  # SQL Admin password secret

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login with Federated Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
          
      # Deployment of template    
      - name: Deploy ARM Template resourcegroup
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          region: eastus # Set this to your target region
          template: repo/templates/azuredeploy.resourcegroup.json
          parameters: repo/templates/azuredeploy.resourcegroup.parameters.json rgName=${{env.AZURE_RESOURCEGROUP_NAME}}

      # Deployment of template    
      - name: Deploy ARM Template resources
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{env.AZURE_RESOURCEGROUP_NAME}}
          region: eastus # Set this to your target region
          template: repo/templates/azuredeploy.json
          parameters: repo/templates/azuredeploy.parameters.json webappName=${{env.AZURE_WEBAPP_NAME}} aspName=${{env.ASP_NAME}} sqlServerName=${{env.SQLSERVER_NAME}} databaseName=${{env.DATABASE_NAME}} sqlAdminLogin=${{env.SQLADMIN_LOGIN}} sqlAdminPass=${{env.SQLADMIN_PASS}}

#TODO: Once the infrastructure is created, download web app publish profile of the staging slot and add it as a secret to the repo. It will be used by the workflow.yml file.
