name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to your default branch if different
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
      # Azure Login
      - name: Azure Login with Federated Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: repo
          
      # Deployment of template    
      - name: Deploy ARM Template resourcegroup
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: eastus # Set this to your target region
          template: repo/templates/azuredeploy.resourcegroup.json
          parameters: repo/templates/azuredeploy.resourcegroup.parameters.json rgName=${{ env.AZURE_RESOURCEGROUP_NAME }}

      # Deployment of resources    
      - name: Deploy ARM Template resources
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          region: centralus # Set this to your target region
          template: repo/templates/azuredeploy.json
          parameters: repo/templates/azuredeploy.parameters.json webappName=${{ env.AZURE_WEBAPP_NAME }} aspName=${{ env.ASP_NAME }} sqlServerName=${{ env.SQLSERVER_NAME }} databaseName=${{ env.DATABASE_NAME }} sqlAdminLogin=${{ env.SQLADMIN_LOGIN }} sqlAdminPass=${{ env.SQLADMIN_PASS }}
